<?php

namespace App\Model\ORM;

use Doctrine;
use Nettrine\ORM\EntityManagerDecorator;

class Decorator extends EntityManagerDecorator {

    /**
     * @return Doctrine\ORM\QueryBuilder
     */
    public function createQueryBuilder() {
        return parent::createQueryBuilder(); // TODO: Change the autogenerated stub
    }


}